<form enctype="multipart/form-data" method="post" action="<?= Ptl::url('import') ?>">
    <div class="form-group">
        <label for="trades_file">File:</label>
        <input type="file" class="form-control" name="trades_file" id="trades_file"/>
    </div>
    <div class="form-group">
        <label for="trades_format">Format:</label>
        <select class="form-control" id="trades_format" name="trades_format">
            <option value="dastrader_report" selected="selected">DASTrader Pro Report</option>
        </select>
    </div>
    <div class="form-group">
        <label for="account_id">Account:</label>
        <select class="form-control" id="account_id" name="account_id">
            <?php foreach (Ptl::app()->getConfig('accounts') as $id => $token): ?>
                <option value="<?= $id ?>"><?= $token ?></option>
            <?php endforeach; ?>
        </select>
    </div>
    <input type="hidden" name="action" value="import_trades"/>
    <button type="submit" class="btn btn-default">Import File</button>
</form>