<form method="post" action="<?= Ptl::url('import') ?>">
    <div class="form-group">
        <label for="trade_csv">CSV File:</label>
        <input type="file" class="form-control" name="trade_csv" id="trade_csv"/>
    </div>
    <div class="form-group">
        <label for="csv_format">File Format:</label>
        <select class="form-control" id="csv_format" name="csv_format">
            <option value="dastrader_report" selected="selected">DASTrader Pro Report</option>
        </select>
    </div>
    <button type="submit" class="btn btn-default">Import File</button>
</form>