<?php
$links = [
    [
        'label'  => 'Home',
        'page'   => '',
        'action' => '',
    ],
    [
        'label'  => 'Import',
        'page'   => 'import',
        'action' => '',
    ],
];
?>
<div id="navigation">
    <?php foreach ($links as $link): ?>
        <a class="button" href="<?= Ptl::url($link) ?>"><?= Ptl::translate($link['label']) ?></a>
    <?php endforeach; ?>
    <br style="clear: both"/>
</div>
