<table class="table table-bordered">
    <thead>
    <tr>
        <th>Date</th>
        <th>Source</th>
        <th>Symbol</th>
        <th>Type</th>
        <th>Pos Size</th>
        <th>Buy</th>
        <th>Sell</th>
        <th>Sum</th>
        <th>Invest</th>
        <th>Comissions</th>
        <th>Notes</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($this->trades as $trade): ?>
    <?php endforeach; ?>
    </tbody>
</table>